#!/bin/sh
#
# Start network time daemon
#

case "$1" in
  start)
    logger -s "Starting ntpd: "
    if ping -c 1 ntp.nict.jp > /dev/null ; then
      /usr/sbin/ntpd -qn -p ntp.nict.jp
    else
      [ -f /media/mmc/time.ini ] && date -s @`sed -ne 's/utc=//p' /media/mmc/time.ini`
    fi
    /usr/sbin/ntpd -p ntp.nict.jp
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  stop)
    logger -s "Stopping ntpd: "
    killall ntpd
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
