#!/bin/sh

# build kernel and rootfs
cd /atomtools/build/buildroot-2016.02/output
rm -rf target
mkdir -p target/lib
cp -dpf staging/lib/libgcc_s.so* target/lib/
mkdir -p target/usr/lib
cp -dpf staging/usr/lib/libstdc++.so* target/usr/lib/
find ./build -name ".stamp_target_installed*" -print | xargs rm -f
cd /atomtools/build/buildroot-2016.02
if cmp /src/custompackages/package/Config.in package/Config.in ; then
  cp -pr /src/custompackages/package/* package
  make /src/configs/atomcam_defconfig
fi
make
