#!/bin/sh

# build kernel and rootfs
cd /atomtools/build/buildroot-2016.02/output
rm -rf target
mkdir -p target/lib
cp -dpf staging/lib/libgcc_s.so* target/lib/
mkdir -p target/usr/lib
cp -dpf staging/usr/lib/libstdc++.so* target/usr/lib/
find ./build -name ".stamp_target_installed*" -print | xargs rm -f
cd /atomtools/build/buildroot-2016.02
cmp /src/custompackages/package/Config.in package/Config.in || cp /src/configs/atomcam_defconfig .config
for i in `ls /src/custompackages/package`
do
  rm -rf package/$i
  cp -pr /src/custompackages/package/$i package
done
make
